android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.builtInKotlin=true
android.newDsl=true
ksp.useKSP2=true
APP_VERSION_CODE=12
APP_VERSION_NAME=1.1.1

# More headroom now that we have swap
org.gradle.jvmargs=-Xmx2g -Xms256m -XX:MaxMetaspaceSize=512m -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
